### ISSUE TITLE
Unable to install any version > 0.7.0 of nemoguardrails using pipenv install nemoguardrails

### ISSUE THREAD

**Issue by nachiketaa** [NVIDIA/NeMo-Guardrails#571] opened 2024-06-20 23:56 UTC
Getting the following error. Even when trying to install it as the only package in the freshly created environment.

Python version: 3.10

[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: metadata generation failed

    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!

**Comment by Pouyanpi** [comment] 2024-07-11 07:38
Hi @nachiketaa,

Thank you for opening this issue.

I used `pipenv` to install `nemoguardrails` without any issues. Since the problem could be due to various factors, reproducing it might be challenging. Here are a few steps you can try to resolve the issue:

### 1. Clear the Cache

Clearing the cache can resolve many issues related to corrupted dependency data:

```sh
pipenv lock --clear
```

This clears the cache and attempts to lock the dependencies again.

### 2. Upgrade Pipenv

Upgrading to the latest version of Pipenv can resolve bugs and compatibility issues:

```sh
pip install --upgrade pipenv
```

### 3. Recreate the Virtual Environment

Deleting and recreating the virtual environment ensures that you start with a clean slate.



Given that this issue isn't directly related to `nemoguardrails`, I will be closing it for now. If you continue to experience problems, please provide additional details or consider opening a new issue with more specific information.

**Closed by Pouyanpi** 2024-07-11 07:38 UTC
