### ISSUE TITLE
Add the option to disable loading default config

### ISSUE THREAD

**Issue by aptlin** [NVIDIA/NeMo-Guardrails#7] opened 2023-04-28 09:47 UTC
Thanks so much for making this awesome project open-source!
Here is a small pet peeve about the current design: at the moment `from_content` [always loads](https://github.com/NVIDIA/NeMo-Guardrails/blob/9dc5d35b846443a8ea45d32d4c335e58863471be/nemoguardrails/rails/llm/config.py#LL200C3-L200C3) the default instructions, together with the [dir-loading branch](https://github.com/NVIDIA/NeMo-Guardrails/blob/9dc5d35b846443a8ea45d32d4c335e58863471be/nemoguardrails/rails/llm/config.py#L161) of`from_path`. Since the [default config](https://github.com/NVIDIA/NeMo-Guardrails/blob/9dc5d35b846443a8ea45d32d4c335e58863471be/nemoguardrails/rails/llm/default_config.yml) is only relevant for NVIDIA, should we make this behavior opt-in?

**Comment by drazvan** [comment] 2023-04-28 10:21
Hi @aptlin! The default config is not meant to be NVIDIA-specific. In the default sample conversation, the question "Tell me a bit about the history of NVIDIA" is meant as an example of a general question. It could have been "Who invented the internet?" or anything else. Did you notice any unintended behaviour because of that?

Currently, without a sample conversation, the LLM will not perform as well in predicting the canonical forms for user and bot messages. That's why there's the option to override it, by specifying your own, or use the default one. But not remove it completely.

**Comment by aptlin** [comment] 2023-04-28 10:55
Makes sense, thanks! Not sure if it gets overriden though in the cases I've listed above, because `_join_config` just appends the instructions.

**Comment by drazvan** [comment] 2023-04-28 11:24
Indeed, you are right. It does not get overridden. Will push a fix shortly. Thanks for catching this!

**Comment by drazvan** [comment] 2023-04-28 19:08
Should be fixed now. Will be included in the next release. Thanks again!

**Closed by drazvan** 2023-04-28 19:08 UTC
